Feature/customer address crud
tarlrsk/giant-bakery pull request #7
Opened 2023-12-29 06:44 UTC by wpiyaphon

CRUD for customer address

2023-12-29 11:21 UTC, tarlrsk commented on src/app/api/customer-address/route.ts
> +  if (req.method !== "POST") return responseWrapper(400, null, "Not Found");
404

2023-12-29 11:23 UTC, Pan-1245 requested changes
Check HTTP status code documentation for more info. 404 is for Not Found not 400.

2023-12-29 11:23 UTC, Pan-1245 commented on src/app/api/customer-address/route.ts
> +  if (req.method !== "POST") return responseWrapper(400, null, "Not Found");
No need to check for api method

2023-12-29 11:23 UTC, Pan-1245 commented on src/app/api/customer-address/[id]/route.ts
> +      // TODO: This should be userId. Currently userId is nullable, so it is addressId only for testing purposes
Try it after authentication is merged

2024-01-02 10:01 UTC, Pan-1245 commented
@wpiyaphon This should be good. After the postman is done DM me. We can merge this once it is done.

2024-01-02 10:02 UTC, Pan-1245 approved these changes
LGTM

2024-01-02 10:03 UTC, Pan-1245 commented
@tarlrsk Fix vercel please

2024-01-02 11:00 UTC, Pan-1245 approved these changes

2024-01-02 12:27 UTC, merged